# Generated by Django 4.0.4 on 2022-05-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0002_alter_pergunta_data_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='data_pub',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de publicação'),
        ),
    ]
