# Generated by Django 4.0.4 on 2022-08-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
